import 'package:flutter/material.dart';
import 'package:mad_flutter_practicum/domain/model/currency_model.dart';

extension CurrencyNameContextExtension on BuildContext {
  String currencyName(CurrencyModel model) {
    return localizedCurrencyName(model.symbol, Localizations.localeOf(this), fallback: model.name);
  }
}

String localizedCurrencyName(String code, Locale locale, {String? fallback}) {
  final Map<String, String> names = switch (locale.languageCode) {
    'ru' => _ruCurrencyNames,
    'de' => _deCurrencyNames,
    _ => _enCurrencyNames,
  };

  return names[code] ?? fallback ?? code;
}

const Map<String, String> _enCurrencyNames = <String, String>{
  'AED': 'UAE dirham',
  'AMD': 'Armenian dram',
  'AUD': 'Australian dollar',
  'AZN': 'Azerbaijani manat',
  'BDT': 'Bangladeshi taka',
  'BHD': 'Bahraini dinar',
  'BOB': 'Bolivian boliviano',
  'BRL': 'Brazilian real',
  'BYN': 'Belarusian ruble',
  'CAD': 'Canadian dollar',
  'CHF': 'Swiss franc',
  'CNY': 'Chinese yuan',
  'CUP': 'Cuban peso',
  'CZK': 'Czech koruna',
  'DKK': 'Danish krone',
  'DZD': 'Algerian dinar',
  'EGP': 'Egyptian pound',
  'ETB': 'Ethiopian birr',
  'EUR': 'Euro',
  'GBP': 'British pound',
  'GEL': 'Georgian lari',
  'HKD': 'Hong Kong dollar',
  'HUF': 'Hungarian forint',
  'IDR': 'Indonesian rupiah',
  'INR': 'Indian rupee',
  'IRR': 'Iranian rial',
  'JPY': 'Japanese yen',
  'KGS': 'Kyrgyzstani som',
  'KRW': 'South Korean won',
  'KZT': 'Kazakhstani tenge',
  'MDL': 'Moldovan leu',
  'MMK': 'Myanmar kyat',
  'MNT': 'Mongolian tögrög',
  'NGN': 'Nigerian naira',
  'NOK': 'Norwegian krone',
  'NZD': 'New Zealand dollar',
  'OMR': 'Omani rial',
  'PLN': 'Polish zloty',
  'QAR': 'Qatari riyal',
  'RON': 'Romanian leu',
  'RSD': 'Serbian dinar',
  'SAR': 'Saudi riyal',
  'SEK': 'Swedish krona',
  'SGD': 'Singapore dollar',
  'THB': 'Thai baht',
  'TJS': 'Tajikistani somoni',
  'TMT': 'Turkmenistani manat',
  'TRY': 'Turkish lira',
  'UAH': 'Ukrainian hryvnia',
  'USD': 'US dollar',
  'UZS': 'Uzbekistani som',
  'VND': 'Vietnamese dong',
  'XDR': 'Special drawing rights',
  'ZAR': 'South African rand',
};

const Map<String, String> _ruCurrencyNames = <String, String>{
  'AED': 'Дирхам ОАЭ',
  'AMD': 'Армянский драм',
  'AUD': 'Австралийский доллар',
  'AZN': 'Азербайджанский манат',
  'BDT': 'Бангладешская така',
  'BHD': 'Бахрейнский динар',
  'BOB': 'Боливиано',
  'BRL': 'Бразильский реал',
  'BYN': 'Белорусский рубль',
  'CAD': 'Канадский доллар',
  'CHF': 'Швейцарский франк',
  'CNY': 'Китайский юань',
  'CUP': 'Кубинское песо',
  'CZK': 'Чешская крона',
  'DKK': 'Датская крона',
  'DZD': 'Алжирский динар',
  'EGP': 'Египетский фунт',
  'ETB': 'Эфиопский быр',
  'EUR': 'Евро',
  'GBP': 'Британский фунт',
  'GEL': 'Грузинский лари',
  'HKD': 'Гонконгский доллар',
  'HUF': 'Венгерский форинт',
  'IDR': 'Индонезийская рупия',
  'INR': 'Индийская рупия',
  'IRR': 'Иранский риал',
  'JPY': 'Японская иена',
  'KGS': 'Киргизский сом',
  'KRW': 'Южнокорейская вона',
  'KZT': 'Казахстанский тенге',
  'MDL': 'Молдавский лей',
  'MMK': 'Мьянманский кьят',
  'MNT': 'Монгольский тугрик',
  'NGN': 'Нигерийская найра',
  'NOK': 'Норвежская крона',
  'NZD': 'Ново-зеландский доллар',
  'OMR': 'Оманский риал',
  'PLN': 'Польский злотый',
  'QAR': 'Катарский риял',
  'RON': 'Румынский лей',
  'RSD': 'Сербский динар',
  'SAR': 'Саудовский риял',
  'SEK': 'Шведская крона',
  'SGD': 'Сингапурский доллар',
  'THB': 'Тайский бат',
  'TJS': 'Таджикский сомони',
  'TMT': 'Туркменский манат',
  'TRY': 'Турецкая лира',
  'UAH': 'Украинская гривна',
  'USD': 'Доллар США',
  'UZS': 'Узбекский сум',
  'VND': 'Вьетнамский донг',
  'XDR': 'Специальные права заимствования',
  'ZAR': 'Южноафриканский ранд',
};

const Map<String, String> _deCurrencyNames = <String, String>{
  'AED': 'VAE-Dirham',
  'AMD': 'Armenischer Dram',
  'AUD': 'Australischer Dollar',
  'AZN': 'Aserbaidschanischer Manat',
  'BDT': 'Bangladesch-Taka',
  'BHD': 'Bahraini-Dinar',
  'BOB': 'Bolivianischer Boliviano',
  'BRL': 'Brasilianischer Real',
  'BYN': 'Belarussischer Rubel',
  'CAD': 'Kanadischer Dollar',
  'CHF': 'Schweizer Franken',
  'CNY': 'Chinesischer Yuan',
  'CUP': 'Kubanischer Peso',
  'CZK': 'Tschechische Krone',
  'DKK': 'Dänische Krone',
  'DZD': 'Algerischer Dinar',
  'EGP': 'Ägyptisches Pfund',
  'ETB': 'Äthiopischer Birr',
  'EUR': 'Euro',
  'GBP': 'Britisches Pfund',
  'GEL': 'Georgischer Lari',
  'HKD': 'Hongkong-Dollar',
  'HUF': 'Ungarischer Forint',
  'IDR': 'Indonesische Rupiah',
  'INR': 'Indische Rupie',
  'IRR': 'Iranischer Rial',
  'JPY': 'Japanischer Yen',
  'KGS': 'Kirgisischer Som',
  'KRW': 'Südkoreanischer Won',
  'KZT': 'Kasachischer Tenge',
  'MDL': 'Moldauischer Leu',
  'MMK': 'Myanmarscher Kyat',
  'MNT': 'Mongolischer Tögrög',
  'NGN': 'Nigerianische Naira',
  'NOK': 'Norwegische Krone',
  'NZD': 'Neuseeländischer Dollar',
  'OMR': 'Omanischer Rial',
  'PLN': 'Polnischer Złoty',
  'QAR': 'Katar-Riyal',
  'RON': 'Rumänischer Leu',
  'RSD': 'Serbischer Dinar',
  'SAR': 'Saudi-Riyal',
  'SEK': 'Schwedische Krone',
  'SGD': 'Singapur-Dollar',
  'THB': 'Thailändischer Baht',
  'TJS': 'Tadschikischer Somoni',
  'TMT': 'Turkmenischer Manat',
  'TRY': 'Türkische Lira',
  'UAH': 'Ukrainische Hrywnja',
  'USD': 'US-Dollar',
  'UZS': 'Usbekischer Som',
  'VND': 'Vietnamesischer Dong',
  'XDR': 'Sonderziehungsrechte',
  'ZAR': 'Südafrikanischer Rand',
};

